app = "bytebooks-backend"
primary_region = "gru"

[[mounts]]
  source      = "data"
  destination = "/data"

[env]
  PORT                      = "8000"
  SQLITE_PATH               = "/data/db.sqlite3"
  DJANGO_SUPERUSER_USERNAME = "admin"

[http_service]
  internal_port = 8000
  force_https   = true

[deploy]
  release_command = "bash -c 'python manage.py migrate --noinput && python manage.py createsuperuser --no-input || true'"

  [[deploy.mounts]]
    source      = "data"
    destination = "/data"
