app = "bytebooks-backend"
primary_region = "gru"

[[mounts]]
  source      = "data"
  destination = "/data"

[env]
  PORT                      = "8000"
  SQLITE_PATH               = "/data/db.sqlite3"
  DJANGO_SUPERUSER_USERNAME = "admin"
  DJANGO_SUPERUSER_EMAIL    = "admin@bytebooks.dev"
  DJANGO_SUPERUSER_PASSWORD = "SenhaAdm123@"

[http_service]
  internal_port = 8000
  force_https   = true

[deploy]
  # migrações + superuser (static já coletado na build)
  release_command = "bash -c 'python manage.py migrate --noinput && python manage.py createsuperuser --no-input || true'"
