app = "bytebooks-backend"
primary_region = "gru"
console_command = "/code/manage.py shell"

[[mounts]]
  source      = "data"
  destination = "/data"

[build]

[env]
  PORT                       = "8000"
  SQLITE_PATH                = "/data/db.sqlite3"
  DJANGO_SUPERUSER_USERNAME  = "admin"
  DJANGO_SUPERUSER_EMAIL     = "admin@bytebooks.dev"
  DJANGO_SUPERUSER_PASSWORD  = "SenhaAdm123@"
  STATIC_ROOT = "/data/staticfiles"

[http_service]
  internal_port      = 8000
  force_https        = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes          = ["app"]

[[vm]]
  memory    = "1gb"
  cpu_kind  = "shared"
  cpus      = 1

[deploy]
  release_command = "bash -c 'python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py createsuperuser --no-input || true'"

