# Generated by Django 5.1.3 on 2025-04-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0013_alter_combo_descricao_alter_combo_descricaodetalhada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('tempoCriacaoCarrinho', models.DateTimeField(auto_now_add=True)),
                ('listaLivros', models.ManyToManyField(to='livros.livro')),
            ],
        ),
    ]
