# Generated by Django 5.1.3 on 2024-12-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_nome_cliente_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dataNascimento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
