# Generated by Django 5.1.3 on 2024-12-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_datanascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
