# Generated by Django 5.1.3 on 2025-04-16 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_datanascimento'),
        ('livros', '0013_alter_combo_descricao_alter_combo_descricaodetalhada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCompra', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='livrosComprados',
            field=models.ManyToManyField(related_name='compradores', through='clientes.Compra', to='livros.livro'),
        ),
    ]
