# Generated by Django 5.1.3 on 2025-04-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
