# Generated by Django 5.1.2 on 2024-10-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('autor', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('descricao', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('qtd', models.IntegerField(default=0)),
                ('disponibilidade', models.BooleanField(default=False)),
            ],
        ),
    ]
