# Generated by Django 5.1.3 on 2025-05-05 03:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('autor', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chamadaDesc', models.CharField(default='', max_length=500)),
                ('descricao', models.TextField(default='', max_length=5000)),
                ('categoria', models.CharField(max_length=100)),
                ('estoque', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='imgsLivros/')),
                ('qtdVendas', models.IntegerField(default=0)),
                ('dataLancamento', models.DateField(default=django.utils.timezone.now)),
                ('dataLancamentoLoja', models.DateField(default=django.utils.timezone.now)),
                ('avaliacaoGeral', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('qtdAvaliacoes', models.IntegerField(default=0)),
                ('qtdPaginas', models.IntegerField(default=0)),
                ('editora', models.CharField(default='', max_length=100)),
                ('idioma', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloCombo', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chamadaDesc', models.CharField(default='', max_length=500)),
                ('descricao', models.TextField(default='', max_length=5000)),
                ('descricaoDetalhada', models.TextField(default='', max_length=5000)),
                ('dataLancamentoLoja', models.DateField(default=django.utils.timezone.now)),
                ('qtdVendas', models.IntegerField(default=0)),
                ('livros', models.ManyToManyField(to='livros.livro')),
            ],
        ),
    ]
