# Generated by Django 5.1.3 on 2025-05-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('dados', 'Dados'), ('backend', 'Backend'), ('software', 'Software')], default='software', max_length=10),
        ),
    ]
