# Generated by Django 5.1.3 on 2025-05-05 04:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='chamadaDesc',
            field=models.CharField(default='', max_length=500, verbose_name='Descrição curta (Home)'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='dataLancamentoLoja',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Disponível na loja em'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='descricao',
            field=models.TextField(default='', max_length=5000, verbose_name='Descrição completa'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='descricaoDetalhada',
            field=models.TextField(default='', max_length=5000, verbose_name='Descrição detalhada'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='livros',
            field=models.ManyToManyField(to='livros.livro', verbose_name='Livros incluídos'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do combo (R$)'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='qtdVendas',
            field=models.IntegerField(default=0, verbose_name='Quantidade de vendas'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='tituloCombo',
            field=models.CharField(max_length=100, verbose_name='Título do combo'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='avaliacaoGeral',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação média (0-5)'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('dados', 'Ciência de Dados'), ('backend', 'Desenvolvimento Back-End'), ('software', 'Engenharia de Software')], default='software', max_length=10, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='chamadaDesc',
            field=models.CharField(default='', max_length=500, verbose_name='Descrição curta (Home)'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='dataLancamento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de lançamento'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='dataLancamentoLoja',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Disponível na loja em'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(default='', max_length=5000, verbose_name='Descrição completa'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(default='', max_length=100, verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='idioma',
            field=models.CharField(default='', max_length=100, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='img',
            field=models.ImageField(upload_to='imgsLivros/', verbose_name='Imagem da capa'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='qtdAvaliacoes',
            field=models.IntegerField(default=0, verbose_name='Número de avaliações'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='qtdPaginas',
            field=models.IntegerField(default=0, verbose_name='Quantidade de páginas'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='qtdVendas',
            field=models.IntegerField(default=0, verbose_name='Quantidade de vendas'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
    ]
