# Generated by Django 5.1.3 on 2025-05-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_combo_chamadadesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='descricaoDetalhada',
            field=models.TextField(default='', max_length=5000, verbose_name='O que o combo contém?'),
        ),
    ]
