# Generated by Django 5.1.1 on 2024-10-31 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_remove_livro_disponibilidade_livro_qtdvendida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='qtd',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='qtdVendida',
            new_name='qtdVendas',
        ),
    ]
