# Generated by Django 5.1.1 on 2024-10-31 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_rename_qtd_livro_estoque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='dataLancamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
