# Generated by Django 5.1.3 on 2024-11-17 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_alter_livro_avaliacaogeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='dataLancamentoLoja',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
