# Generated by Django 5.1.3 on 2024-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_alter_livro_preco_combo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='livros',
        ),
        migrations.AddField(
            model_name='combo',
            name='livros',
            field=models.ManyToManyField(to='livros.livro'),
        ),
    ]
