# Generated by Django 5.1.3 on 2024-11-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_remove_combo_livros_combo_livros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='img',
        ),
    ]
