# Generated by Django 5.1.3 on 2024-12-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0011_remove_combo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='descricaoDetalhada',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='livro',
            name='idoma',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='livro',
            name='qtdPaginas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='combo',
            name='descricao',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
    ]
