# Generated by Django 5.1.3 on 2025-04-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0012_combo_chamadadesc_combo_descricaodetalhada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='descricao',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='combo',
            name='descricaoDetalhada',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
