# Generated by Django 5.1.3 on 2024-12-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0014_combo_chamadadesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='idoma',
            new_name='idioma',
        ),
    ]
