# Generated by Django 5.1.3 on 2024-12-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0015_rename_idoma_livro_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='descricao',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='combo',
            name='descricaoDetalhada',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
